// Load a previously-generated deck back from the local-dir backend
// (generated/<deckId>/). The "Load it" / "Reload deck" buttons of prompt-export
// mode use this to pull in a deck that a Claude Code session wrote (or modified)
// on disk. Node-only (reads node:fs via ./storage). In dev it's mounted at
// /api/load-generated by vite.config.ts.

import { readDeck } from "./storage";
import type { GeneratedDeck } from "../../shared/generation";

export interface LoadGeneratedRequest {
  deckId: string;
}

export async function handleLoadGenerated(req: LoadGeneratedRequest): Promise<GeneratedDeck> {
  const deckId = (req?.deckId ?? "").trim();
  if (!deckId) throw new Error("A deckId is required to load a generated deck.");
  const found = await readDeck(deckId);
  if (!found) {
    throw new Error(`No generated deck found at generated/${deckId}/ (has Claude Code written it yet?).`);
  }
  return {
    deckId,
    files: found.files,
    brief: found.brief,
    message: "Loaded the deck from generated/" + deckId + "/.",
    mock: true,
  };
}
