// Serverless entry point for loading a generated deck from the local-dir backend.
// Like api/generate.ts, this reads node:fs (api/_generation/storage.ts) so it needs
// a Node function runtime, NOT edge. In dev the same handler is mounted at
// /api/load-generated by vite.config.ts.

import { handleLoadGenerated } from "./_generation/load";

export default async function handler(request: Request): Promise<Response> {
  if (request.method !== "POST") {
    return new Response("Method Not Allowed", { status: 405 });
  }
  try {
    const body = await request.json();
    const result = await handleLoadGenerated(body);
    return new Response(JSON.stringify(result), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: String((err as Error)?.message ?? err) }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }
}
